
trigger:
- master

pr:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $versionFull = "$(Build.BuildNumber)"
      $version = $versionFull|%{[System.Version]$_}
      $versionShort = "$($version.Major).$($version.Minor).$($version.Build)"
      $versionTemplate = "111.111.111"
      $files = "./AddinSetup/AddinSetup.wxs", "./AddinSetup/AddinSetup.wixproj"
      $files | ForEach-Object {
        $file = $_
        (Get-Content $file) | ForEach-Object { $_ -replace $versionTemplate, $versionShort } | Set-Content $file
      }
      Write-Host "##vso[task.setvariable variable=versionShort]$($versionShort)"

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x86'
    configuration: 'Release'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x64'
    configuration: 'Release'
