
trigger:
- master

pr:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Write-Host "Hello World"

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x86'
    configuration: 'Release'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x64'
    configuration: 'Release'
