# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pr:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'

steps:

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x86'
    configuration: 'Release'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x64'
    configuration: 'Release'
